# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        

      # Runs a single command using the runners shell
      - name: Remove existing builds
        run: rm -rf wine64-build wine32-build
      - name: mkdir wine64-build wine32-build
        run: mkdir wine64-build wine32-build
      - run: export REPODIR=$(pwd)
      - run: echo $REPODIR
      - run: |
          podman run --name centos8stream -v `pwd`:`pwd`:z -w `pwd` -d -t quay.io/centos/centos:stream8 /bin/sh

          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes config-manager --enable powertools -y"
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes update"
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes -y install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y"
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes -y install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm -y"
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes update &&  dnf --skip-broken --assumeyes install alsa-lib-devel.i686 alsa-plugins-pulseaudio.i686 bzip2-devel.x86_64 cups-devel.i686 flac-libs.i686 fontconfig-devel.i686 freetype-devel.i686 freetype-devel.x86_64 glib2-devel.i686 glibc-devel.i686 glibc-devel.x86_64 glibc-headers.i686 gnutls-devel.i686 gsm-devel.i686 gstreamer-devel.i686 gstreamer-devel.x86_64 gstreamer-ffmpeg.i686 gstreamer-plugins-base-devel.i686 gstreamer-plugins-base-devel.x86_64 gstreamer-plugins-base.i686 gstreamer-plugins-base.x86_64 gstreamer.i686 gstreamer.x86_64 gstreamer1-devel.i686 gstreamer1-devel.x86_64 gstreamer1-libav.i686 gstreamer1-plugins-bad-free-devel.i686 gstreamer1-plugins-bad-free-extras.i686 gstreamer1-plugins-bad-freeworld.i686 gstreamer1-plugins-base-devel.i686 gstreamer1-plugins-base-devel.x86_64 gstreamer1-plugins-good-extras.i686 gstreamer1.i686 gtk3-devel.i686 json-c.i686 lcms2-devel.i686 libFAudio-devel.i686 libFAudio-devel.x86_64 libICE.i686 libSM.i686 libX11-devel.i686 libX11-devel.x86_64 libXau-devel.x86_64 libXcomposite-devel.i686 libXcursor-devel.i686 libXext-devel.i686 libXi-devel.i686 libXinerama-devel.i686 libXrandr-devel.i686 libXrender-devel.i686 libXtst.i686 libXxf86vm-devel.i686 libasyncns.i686 libattr-devel.i686 libcom_err-devel.i686 libcom_err-devel.x86_64 libedit.i686 liberation-narrow-fonts.noarch libexif-devel.i686 libexif.i686 libgcc.i686 libgphoto2-devel.i686 libieee1284.i686 libjpeg-turbo-devel.i686 libogg.i686 libpcap-devel.i686 libpkgconf.i686 libpng-devel.i686 libpng-devel.x86_64 libsndfile.i686 libtiff-devel.i686 libuuid.i686 libv4l-devel.i686 libva-devel.i686 libva.i686 libvorbis.i686 libwayland-client.i686 libwayland-server.i686 libxcb-devel.x86_64 libxcrypt-devel.i686 libxml2-devel.i686 libxslt-devel.i686 libzip-devel.i686 llvm-libs.i686 mesa-dri-drivers.i686 mesa-filesystem.i686 mesa-libEGL.i686 mesa-libGL-devel.i686 mesa-libGLU-devel.i686 mesa-libOSMesa-devel.i686 mesa-libOpenCL-devel.i686 mesa-libgbm.i686 mpg123-devel.i686 mpg123-devel.x86_64 ncurses-devel.i686 nss-mdns.i686 ocl-icd.i686 openal-soft-devel.i686 opencl-utils-devel.i686 openldap-devel.i686 pkgconf-pkg-config.i686 pkgconf.i686 pulseaudio-libs-devel.i686 pulseaudio-libs-devel.x86_64 pulseaudio-libs.i686 samba-common-tools.x86_64 samba-libs.x86_64 samba-winbind-clients.x86_64 samba-winbind-modules.x86_64 samba-winbind.x86_64 sane-backends-libs.i686 tcp_wrappers-libs.i686 unixODBC.i686 xorg-x11-proto-devel.noarch zlib-devel.i686"
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes groupinstall \"C Development Tools and Libraries\""
          podman exec centos8stream  sh -c  "dnf --skip-broken --assumeyes groupinstall \"Development Tools\""
          podman exec centos8stream  sh -c  "ls /usr/lib"
          podman exec centos8stream  sh -c  "pwd"
          podman exec centos8stream  sh -c  "cd wine64-build && pwd && ../configure --enable-win64 && make"
          podman exec centos8stream  sh -c  "cd wine32-build && pwd && PKG_CONFIG_PATH=/usr/lib/pkgconfig ../configure --with-wine64=../wine64-build && make"
#       - run: docker exec -it --volume $(pwd):/tmp/repodir

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
